name: msa_tool
channels:
  #- pytorch
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  #- torch
  - pandas
  - numpy
  - requests
  - scipy
  - fair-esm
  - matplotlib
  - biopython
  - biotite
  - scikit-learn
  - optuna
  - seaborn
  - openpyxl
  - xmltramp2
  - clustalo
  - mmseqs2
